language: java
jdk:
  - oraclejdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_install:
- mvn test -B

script:
  - run Backbase-Testing-Framework.iml  --reporter-html-export output/htmlCIResults.html
